# Generated by Django 3.0.6 on 2020-05-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20200519_1359'),
        ('organisations', '0005_auto_20200519_1425'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classe',
        ),
    ]
