# Generated by Django 3.0.6 on 2020-05-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_class_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='photo',
            field=models.ImageField(upload_to='classes/'),
        ),
    ]
