# Generated by Django 3.0.6 on 2020-05-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_class_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='organisation',
        ),
    ]
