# Generated by Django 3.0.6 on 2020-05-23 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_organisation_administrator'),
        ('classes', '0009_class_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
    ]
