# Generated by Django 3.0.6 on 2020-05-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_class_sub_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='sub_heading',
            new_name='subject',
        ),
    ]
