# Generated by Django 3.0.6 on 2020-05-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_auto_20200527_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='subject',
        ),
    ]
