# Generated by Django 3.0.6 on 2020-06-06 16:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_auto_20200606_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='date_And_Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 16, 15, 15, 386884, tzinfo=utc), help_text='Date and Time will be used for future weeks.'),
        ),
        migrations.AlterField(
            model_name='class',
            name='language',
            field=models.CharField(default='en-us', max_length=200),
        ),
    ]
