# Generated by Django 3.0.6 on 2020-06-06 16:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0020_auto_20200606_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='date_And_Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 16, 36, 50, 316904, tzinfo=utc), help_text='Date and Time will be used for future weeks.'),
        ),
        migrations.AlterField(
            model_name='class',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 means free and decimal point integers otherwise.', max_digits=6),
        ),
    ]
