# Generated by Django 3.0.6 on 2020-06-06 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0021_auto_20200606_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='sub_Heading',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='class',
            name='date_And_Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 16, 39, 16, 657576, tzinfo=utc), help_text='Date and Time will be used for future weeks.'),
        ),
    ]
