# Generated by Django 3.0.6 on 2020-06-06 16:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0022_auto_20200606_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='date_And_Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 16, 41, 29, 2028, tzinfo=utc), help_text='The day and time from Date/Time, will be used for future weeks.'),
        ),
    ]
