# Generated by Django 3.0.6 on 2020-06-06 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0023_auto_20200606_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='date_And_Time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The day and time from Date/Time, will be used for future weeks.'),
        ),
    ]
