# Generated by Django 3.0.6 on 2020-06-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0026_auto_20200610_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='sub_Heading',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='class',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
