# Generated by Django 3.0.6 on 2020-06-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0027_auto_20200610_0710'),
        ('classes', '0027_auto_20200610_0715'),
    ]

    operations = [
    ]
