# Generated by Django 3.0.6 on 2020-06-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0028_merge_20200612_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='title',
            field=models.CharField(max_length=28),
        ),
    ]
