# Generated by Django 3.0.6 on 2020-06-12 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0029_auto_20200612_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.TextField(help_text='Maximum of 132 characters.', max_length=132, validators=[django.core.validators.MinLengthValidator(132)]),
        ),
    ]
