# Generated by Django 3.0.6 on 2020-06-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0030_auto_20200612_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='language',
            field=models.CharField(default='English', max_length=20),
        ),
    ]
