# Generated by Django 3.0.6 on 2020-06-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0031_auto_20200612_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='photo',
            field=models.ImageField(default='classes/', help_text='Must be a height and width of 200px', upload_to='classes/'),
        ),
    ]
