# Generated by Django 3.0.6 on 2020-06-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0033_auto_20200612_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='title',
            field=models.CharField(help_text='Max 30 characters', max_length=28),
        ),
    ]
