# Generated by Django 3.0.6 on 2020-06-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0038_auto_20200619_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='sub_Heading',
            field=models.CharField(blank=True, help_text='Max 40 characters', max_length=40),
        ),
    ]
