# Generated by Django 3.0.6 on 2020-05-17 13:08

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('countries', django_countries.fields.CountryField(max_length=2)),
                ('types', models.CharField(blank=True, choices=[('Student of Knowledge', 'Student of Knowledge'), ('Scholar', 'Scholar')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
