# Generated by Django 3.0.6 on 2020-05-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='countries',
            new_name='country',
        ),
    ]
