# Generated by Django 3.0.6 on 2020-05-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20200519_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='types',
            new_name='type',
        ),
    ]
