# Generated by Django 3.0.6 on 2020-05-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20200519_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='type',
            field=models.CharField(choices=[('Student of Knowledge', 'Student of Knowledge'), ('Scholar', 'Scholar')], max_length=200),
        ),
    ]
