# Generated by Django 3.0.6 on 2020-05-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20200521_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='type',
            field=models.CharField(choices=[('Student of Knowledge', 'Student of Knowledge'), ('Scholar', 'Scholar')], max_length=20),
        ),
    ]
