# Generated by Django 3.0.6 on 2020-05-26 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20200521_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teachers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher'),
        ),
    ]
