# Generated by Django 3.0.6 on 2020-05-26 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_teacher_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teachers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher'),
        ),
    ]
