# Generated by Django 3.0.6 on 2020-05-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_auto_20200526_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teachers',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_teacher_teachers_+', to='teachers.Teacher'),
        ),
    ]
