# Generated by Django 3.0.6 on 2020-05-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_auto_20200526_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
    ]
