# Generated by Django 3.0.6 on 2020-05-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_teacher_is_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
