# Generated by Django 3.0.6 on 2020-05-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_auto_20200526_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='website',
        ),
    ]
