# Generated by Django 3.0.6 on 2020-05-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_remove_teacher_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teachers',
        ),
        migrations.AddField(
            model_name='teacher',
            name='_teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_teacher__teachers_+', to='teachers.Teacher'),
        ),
    ]
