# Generated by Django 3.0.6 on 2020-05-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_auto_20200527_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='_teacher_teachers_+', to='teachers.Teacher'),
        ),
    ]
