# Generated by Django 3.0.6 on 2020-06-12 18:06

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import lectures.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0016_auto_20200606_2128'),
        ('organisations', '0015_remove_organisation_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max 30 characters', max_length=28)),
                ('description', models.TextField(max_length=132, validators=[django.core.validators.MinLengthValidator(132)])),
                ('date_And_Time', models.DateTimeField(default=datetime.datetime.today)),
                ('expiration_Date_And_Time', models.DateTimeField(default=lectures.models.one_day)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('language', models.CharField(default='English', max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True)),
                ('photo', models.ImageField(default='lectures/', help_text='Must be a height and width of 200px', upload_to='lectures/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation')),
                ('teacher', models.ManyToManyField(to='teachers.Teacher')),
            ],
        ),
    ]
