# Generated by Django 3.0.6 on 2020-05-25 06:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0005_auto_20200521_1931'),
        ('organisations', '0010_auto_20200523_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration', models.DurationField(default=datetime.timedelta(0))),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('language', models.CharField(default='English', max_length=200)),
                ('is_online', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True)),
                ('photo', models.ImageField(default='lectures/', upload_to='lectures/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.Teacher')),
            ],
        ),
    ]
