# Generated by Django 3.0.6 on 2020-05-25 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='expiration',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
