# Generated by Django 3.0.6 on 2020-06-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_auto_20200612_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='photo',
            field=models.ImageField(default='lectures/', help_text='Must be a height, width of 200px and image size under 20KB.', upload_to='lectures/'),
        ),
    ]
