# Generated by Django 3.0.6 on 2020-05-25 06:55

from django.db import migrations, models
import lectures.models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_auto_20200525_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='expiration_days',
        ),
        migrations.AddField(
            model_name='lecture',
            name='expiration_date',
            field=models.DateField(default=lectures.models.one_day),
        ),
    ]
