# Generated by Django 3.0.6 on 2020-05-25 15:59

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_auto_20200525_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='datetime',
        ),
        migrations.AddField(
            model_name='lecture',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='lecture',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
