# Generated by Django 3.0.6 on 2020-06-07 22:27

import datetime
from django.db import migrations, models
import lectures.models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0009_auto_20200528_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='time',
        ),
        migrations.AddField(
            model_name='lecture',
            name='date_And_Time',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='lecture',
            name='expiration_Date_And_Time',
            field=models.DateTimeField(default=lectures.models.one_day),
        ),
    ]
