# Generated by Django 3.0.6 on 2020-05-18 18:21

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='mixlr',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='soundcloud',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='telegram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
