# Generated by Django 3.0.6 on 2020-05-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20200518_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='phone',
            field=models.CharField(default='Please enter phone Number', max_length=100),
        ),
    ]
