# Generated by Django 3.0.6 on 2020-05-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_organisation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
