# Generated by Django 3.0.6 on 2020-05-19 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_auto_20200519_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='organisation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
