# Generated by Django 3.0.6 on 2020-05-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_auto_20200519_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='photo_main',
            field=models.ImageField(default='photos/', upload_to='photos/'),
        ),
    ]
