# Generated by Django 3.0.6 on 2020-05-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_organisation_photo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='photo_1',
            field=models.ImageField(blank=True, default='photos/<django.db.models.fields.CharField>/', upload_to='photos/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='photo_2',
            field=models.ImageField(blank=True, default='photos/<django.db.models.fields.CharField>/', upload_to='photos/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='photo_3',
            field=models.ImageField(blank=True, default='photos/<django.db.models.fields.CharField>/', upload_to='photos/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='photo_4',
            field=models.ImageField(blank=True, default='photos/<django.db.models.fields.CharField>/', upload_to='photos/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='photo_5',
            field=models.ImageField(blank=True, default='photos/<django.db.models.fields.CharField>/', upload_to='photos/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(upload_to='logos/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='photo_main',
            field=models.ImageField(default='photos/<django.db.models.fields.CharField>/', upload_to='photos/<django.db.models.fields.CharField>/'),
        ),
    ]
