# Generated by Django 3.0.6 on 2020-05-22 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0003_remove_administrator_organisation'),
        ('organisations', '0008_auto_20200522_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='administrator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrators.Administrator'),
        ),
    ]
