# Generated by Django 3.0.6 on 2020-05-23 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0003_remove_administrator_organisation'),
        ('organisations', '0009_organisation_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='administrator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrators.Administrator'),
        ),
    ]
