# Generated by Django 3.0.6 on 2020-06-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0014_auto_20200528_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='administrator',
        ),
    ]
