# Generated by Django 3.0.6 on 2020-06-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0015_remove_organisation_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='photo_main',
            field=models.ImageField(default='photos/', help_text='Photo for profile page.', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
