# Generated by Django 3.0.6 on 2020-06-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0017_auto_20200613_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(help_text='Must be a height, width of 200px and image size under 20KB.', upload_to='logos/'),
        ),
    ]
