# Generated by Django 3.0.6 on 2020-06-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0019_auto_20200619_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='types',
            field=models.CharField(choices=[('Centre', 'Centre'), ('School', 'School'), ('Store', 'Store'), ('Pilgrimage', 'Pilgrimage')], max_length=20),
        ),
    ]
